### ISSUE TITLE
Not able to set class for homepage

### ISSUE THREAD

**Issue by nikolaynesov** [nikolaynesov/vue-body-class#2]
As @ktmud mentioned earlier, there is no way to assign a class to body on home page ( "/" route).

**Comment by jgrandar** [comment]
I need a class for homepage too.

**Comment by nikolaynesov** [comment]
@ktmud @jgrandar there is https://github.com/nikolaynesov/vue-body-class/releases/tag/2.0.0-alpha update.

**Comment by jgrandar** [comment]
Many thanks @nikolaynesov, I'll give it a shoot as soon as needed.
