### ISSUE TITLE
Classes are not added

### ISSUE THREAD

**Issue by kriss145** [nikolaynesov/vue-body-class#4]
Hello,

Installed by CLI Vue
Versions from package:
    "vue": "^2.5.2",
    "vue-body-class": "^2.0.0-beta.2",
    "vue-router": "^3.0.1"

I added your code to my first project and I don't see any classes in the body.

My index.js

`import Vue from 'vue'
import Router from 'vue-router'
import vbclass from 'vue-body-class'
import HelloWorld from '@/components/HelloWorld'
import PageSecond from '@/components/PageSecond'

Vue.use(Router, vbclass)

export default new Router({
  mode: 'history',
  routes: [
    {
      path: '/',
      name: 'Hello',
      meta: { bodyClass: 'home' },
      component: HelloWorld
    },
    {
      path: '/page-second',
      name: 'Pages Second',
      meta: { bodyClass: 'page-second' },
      component: PageSecond
    }
  ]
})`

Do you know why is happened?

Thanks!

**Comment by nikolaynesov** [comment]
@kriss145 you must define the router first.

`const router = new VueRouter ...`
and then 
`Vue.use( vbclass, router );`
Let me know if you still need help.
