### ISSUE TITLE
Uncaught TypeError: router.beforeEach is not a function

### ISSUE THREAD

**Issue by zaritzki** [nikolaynesov/vue-body-class#8]
Hello,

New with vue, I have this error when using this.

Error:
Uncaught TypeError: router.beforeEach is not a function

code

import Vue from 'vue'
import Router from 'vue-router'
import vbclass from 'vue-body-class'

import Home from '@/components/Home'

Vue.use( vbclass, Router )
// Vue.use( Router )

export default new Router({
  routes: [
    {
      path: '/',
      name: 'home',
      meta: { bodyClass: 'home' },
      component: Home
    }
]
})

the code seems okay, same with your documentation.

Thanks in advance!

**Comment by baptistebisson** [comment]
Same problem for me.

**Comment by erictronics** [comment]
Same problem here! Please any help?

**Comment by nikolaynesov** [comment]
When did you start getting this error? package.json? versions of package and vue js?  webpack config?

**Comment by hex20** [comment]
Same issue here, I'm using vue-router 3.0.1 would that be the issue?

**Comment by pedroscursel** [comment]
Same issue for me... 
vue-router 2.6.0

**Comment by qntndev** [comment]
Hey guys, here is how to make it works 👍 
Last line is the key !

```javascript
import Router from 'vue-router'
const router = new Router({ 
//config and paths
})
export default router

Vue.use( Router, vbclass)
vbclass.init(router);
```

**Comment by qntndev** [comment]
Hey guys, here is how to make it works 👍 
Last line is the key !

```javascript
import Router from 'vue-router'
import vbclass from 'vue-body-class'
const VueRouter = new Router({ 
//config and paths
})
export default VueRouter

Vue.use( Router )
Vue.use( vbclass, VueRouter )
```

**Comment by macphersonj** [comment]
Same issue, above doesn't work for me

**Comment by macphersonj** [comment]
The answer from @pbredenberg in #3 was what got it working for me.

I had to add `Vue.use(vbclass, router)` in `main.js`, where I was previously adding it to my `router.js`

**Comment by pedroscursel** [comment]
> Hey @pedroscursel, here is how to make it works 👍
> Last line is the key but you need to have your router as a constant.
> Usually templates declare router as `export default new Router({ ... ` so instead you want `const VueRouter = new Router({ ... ` and export it later with `export default VueRouter` .
> 
> ```js
> import Router from 'vue-router'
> import vbclass from 'vue-body-class'
> 
> const VueRouter = new Router({ 
> //config and paths
> })
> export default VueRouter
> 
> Vue.use( Router )
> Vue.use( vbclass, VueRouter )
> ```

Works like a charm :D

**Comment by howdu** [comment]
Get this same error trying to add the backend of laravel-boilerplate. Where do I add the Vue.use to this file?
https://github.com/adr1enbe4udou1n/laravel-boilerplate/blob/master/resources/js/backend/app.js

**Comment by umairqazi523** [comment]
> > Hey @pedroscursel, here is how to make it works 👍
> > Last line is the key but you need to have your router as a constant.
> > Usually templates declare router as `export default new Router({ ... ` so instead you want `const VueRouter = new Router({ ... ` and export it later with `export default VueRouter` .
> > ```js
> > import Router from 'vue-router'
> > import vbclass from 'vue-body-class'
> > 
> > const VueRouter = new Router({ 
> > //config and paths
> > })
> > export default VueRouter
> > 
> > Vue.use( Router )
> > Vue.use( vbclass, VueRouter )
> > ```
> 
> Works like a charm :D

It worked for me 💯

**Comment by nikolaynesov** [comment]
The installation instructions are updated in new version (3.0.1). Please use that instead.
