### ISSUE TITLE
routes.find is not a function

### ISSUE THREAD

**Issue by tylercollier** [nikolaynesov/vue-body-class#9]
**Update** forgot to say I'm using vue-router 3.0.1.

---

I'm seeing this error:

```
TypeError: routes.find is not a function
    at VueBodyClassController.findMatchInRoutesByPath (index.js?c9f8:41)
    at eval (index.js?c9f8:95)
    ...
```

Here's my routes config. I'm doing it this way because I want my Home page to be very different than my subpages, which use a wrapper component named Layout.

```
const routes = [
  { name: 'home', path: '/', component: Home, meta: { bodyClass: 'home' } },
  { path: '', component: Layout, meta: { bodyClass: '!' }, children: [
    { name: 'about', path: '/about', component: About },
    { name: 'contact', path: '/contact', component: Contact },
  ]},
```

A workaround is to put `children: []` on the Home route.

However, the `meta: { bodyClass: '!' }` is not honored; the 'home' css class is still applied to `<body>`.

I'm using vue-body-class 2.0.0-beta.2, and Vue 2.5.3. I am using vue-router 3.0.1 and I see the requirements for this package are vue-router 2.x, so you can close this issue if it's not appropriate/relevant.

**Comment by tylercollier** [comment]
After looking at the source code, the problem of the Layout route's `meta: { bodyClass: '!' }` not being honored is fixed if I put the Home route AFTER the Layout route.

I'm assuming that I'm structuring my routes in a non-standard way. I'd expect if anyone knows a good way to do it, it'd be you :-) How can I create a Home route with its own component, and other children routes that have a Layout wrapper component? (I'm not really asking you to solve my problems, but I'm thinking you're likely to have run into this.)

**Comment by tylercollier** [comment]
I'm not sure how vue-router 2 works, but in Vue router 3, in the route guard, the `to.match` provides the route segments in a flattened array. So there's no need to try to walk down the tree, matching the routes by path (which can be ambiguous anyway because multiple routes can have a path of '`/'` or `''`). I've forked the code and fixed it for my use cases, but I'd appreciate being notified if you update to vue router 3. Thanks!

**Comment by nikolaynesov** [comment]
@tylercollier could you please 3.0.1 and let me know how it works for you. Thanks!
